### ISSUE TITLE
Unit tests missing

### ISSUE THREAD

**Issue by xama5** [cybrox/slack-lunch-bot#1]
The hi method is not covered by unit tests

https://github.com/cybrox/slack-lunch-bot/blob/master/index.js#L9

**Comment by cybrox** [comment]
While this is obviously a horrible flaw, there is some reasoning to be had here.

The `hi` method is merely a fraction of a complex lingual construct that will be implemented in this application's codebase in the future. We are currently conducting extensive research towards how we can safely test this method in a future-proof manner, since the language it exposes is prone to [change](https://www.ling.upenn.edu/courses/Fall_2003/ling001/language_change.html) in the future.

Also, it is unclear if further requirements need to be met in future revisions, since the language used could change altogether due to the unstable nature of the english language. I would propose rewriting the `hi` method to a `bIpIv'a'` method, since Klingon has proven to be much more of a stable language over the past few years.

I will reopen this issue once the language research is concluded and our development team (me) is able (eg. not too lazy) to implement an ample testing solution.
